"""Canonical options for Après user profile questionnaire.

Kept separate from scripts/vibe_taxonomy.py (catalog tags for venues).
"""

from __future__ import annotations

# Cities we support for profile + neighbourhood selection (forced pick).
DEFAULT_CITIES = [
    "Manhattan Beach",
    "Hermosa Beach",
    "Redondo Beach",
    "El Segundo",
    "Torrance",
    "Lawndale",
    "Hawthorne",
    "Gardena",
    "Lomita",
    "Carson",
    "Palos Verdes Estates",
    "Rancho Palos Verdes",
    "Rolling Hills Estates",
    "Playa del Rey",
    "Marina del Rey",
    "Venice",
    "Westchester",
    "Culver City",
    "Santa Monica",
    "Inglewood",
    "Los Angeles",
]

# Neighbourhoods / sections keyed by city. Keep exhaustive for supported cities.
NEIGHBOURHOODS_BY_CITY: dict[str, list[str]] = {
    "Manhattan Beach": [
        "El Porto",
        "Sand Section",
        "Tree Section",
        "Hill Section",
        "Downtown / Pier",
        "The Strand",
        "East Manhattan Beach",
        "Marine Avenue corridor",
        "Polliwog Park area",
    ],
    "Hermosa Beach": [
        "Pier Avenue / Downtown",
        "The Strand",
        "North Hermosa",
        "South Hermosa",
        "Hermosa Valley (Upper Hermosa)",
        "Hermosa Avenue corridor",
    ],
    "Redondo Beach": [
        "North Redondo",
        "South Redondo",
        "Riviera Village",
        "King Harbor / Harbor area",
        "Esplanade",
        "The Pier / International Boardwalk",
        "Avenues / South Bay Galleria area",
        "Torrance Blvd corridor",
    ],
    "El Segundo": [
        "Downtown El Segundo",
        "Smoky Hollow",
        "Hilltop",
        "East El Segundo",
        "Imperial / Beach corridor",
        "Main Street corridor",
    ],
    "Torrance": [
        "Old Torrance",
        "Downtown Torrance",
        "Walteria",
        "Hollywood Riviera",
        "Southwood",
        "West Torrance",
        "East Torrance",
        "Torrance Heights",
        "Madrona",
        "Seaside",
        "Del Amo / Plaza area",
        "New Horizons",
        "Southeast Torrance",
    ],
    "Lawndale": [
        "North Lawndale",
        "South Lawndale",
        "Downtown Lawndale",
        "Marine Avenue corridor",
        "Hawthorne Blvd corridor",
    ],
    "Hawthorne": [
        "Downtown Hawthorne",
        "North Hawthorne",
        "South Hawthorne",
        "Holly Park",
        "Ramona",
        "Bodger Park area",
        "Hawthorne Blvd corridor",
    ],
    "Gardena": [
        "Downtown Gardena",
        "North Gardena",
        "South Gardena",
        "West Gardena",
        "East Gardena",
        "Gardena Blvd corridor",
    ],
    "Lomita": [
        "Downtown Lomita",
        "North Lomita",
        "South Lomita",
        "West Lomita",
        "Pacific Coast Highway corridor",
    ],
    "Carson": [
        "North Carson",
        "South Carson",
        "East Carson",
        "West Carson",
        "Carson Street corridor",
        "Dominguez area",
    ],
    "Palos Verdes Estates": [
        "Malaga Cove",
        "Lunada Bay",
        "Valmonte",
        "Margate",
        "PV Drive corridor",
    ],
    "Rancho Palos Verdes": [
        "Portuguese Bend",
        "Trump National / Oceanfront",
        "Eastview",
        "Ridgecrest",
        "Miraleste",
        "Hesse Park area",
        "PV Drive East / West corridor",
    ],
    "Rolling Hills Estates": [
        "The Village / Peninsula Center",
        "Dapplegray area",
        "Empty Saddle area",
        "PV Drive North corridor",
    ],
    "Playa del Rey": [
        "The Bluffs",
        "Beach / Culver corridor",
        "Surfridge / Dockweiler area",
        "Westchester bluffs edge",
    ],
    "Marina del Rey": [
        "Harbor / Marina waterside",
        "Washington Blvd corridor",
        "Admiralty Way corridor",
        "Villa Marina area",
        "Mother's Beach area",
    ],
    "Venice": [
        "Venice Beach / Boardwalk",
        "Abbot Kinney",
        "Oakwood",
        "Milwood",
        "Silver Triangle",
        "Oxford Triangle",
        "Venice Canals",
        "North Venice",
    ],
    "Westchester": [
        "Downtown Westchester / Loyola",
        "Kentwood",
        "LMU area",
        "Westchester Park area",
        "Airport corridor",
    ],
    "Culver City": [
        "Downtown Culver City",
        "Culver City Arts District",
        "Fox Hills",
        "Blair Hills",
        "Sunkist Park",
        "Culver West",
        "Studio District / Lucerne",
        "Jefferson / Hayden corridor",
    ],
    "Santa Monica": [
        "Downtown / Promenade",
        "Ocean Park",
        "Montana Avenue",
        "North of Montana",
        "Pico",
        "Mid-City",
        "Sunset Park",
        "Wilshire / Montana",
        "Main Street corridor",
    ],
    "Inglewood": [
        "Downtown Inglewood",
        "North Inglewood",
        "Morningside Park",
        "Lockhaven",
        "Centinela area",
        "Forum / SoFi Stadium area",
    ],
    "Los Angeles": [
        "Venice",
        "Mar Vista",
        "Palms",
        "West LA / Sawtelle",
        "Brentwood",
        "Westwood",
        "Century City",
        "Beverly Grove",
        "Mid-Wilshire",
        "Koreatown",
        "Hancock Park",
        "Hollywood",
        "East Hollywood",
        "Los Feliz",
        "Silver Lake",
        "Echo Park",
        "Downtown LA",
        "Arts District",
        "Highland Park",
        "Eagle Rock",
        "Atwater Village",
        "South LA",
        "Crenshaw",
        "Leimert Park",
        "Jefferson Park",
        "Exposition Park",
        "San Pedro",
        "Wilmington",
        "Harbor City",
        "Other LA neighbourhood",
    ],
}

DIETARY_OPTIONS = [
    "None",
    "Vegetarian",
    "Vegan",
    "Gluten-free",
    "Halal",
    "Kosher",
    "Nut allergy",
    "Dairy-free",
    "Pescatarian",
    "Other",
]

ACTIVITY_OPTIONS = [
    "Dining",
    "Coffee & cafes",
    "Wine bars",
    "Cocktail bars",
    "Live music",
    "Rooftop / scenic",
    "Outdoor dining",
    "Casual bites",
    "Fine dining",
    "Nightlife / dancing",
    "Culture / galleries",
    "Wellness",
    "Sports / active",
    "Experiences / tasting menus",
]

# Soft Discover bias: profile activities → Google Places primary_type values.
ACTIVITY_TO_PRIMARY_TYPES: dict[str, tuple[str, ...]] = {
    "Dining": (
        "restaurant",
        "american_restaurant",
        "italian_restaurant",
        "mexican_restaurant",
        "japanese_restaurant",
        "chinese_restaurant",
        "thai_restaurant",
        "french_restaurant",
        "greek_restaurant",
        "seafood_restaurant",
        "sushi_restaurant",
        "steak_house",
        "pizza_restaurant",
        "brunch_restaurant",
        "breakfast_restaurant",
        "diner",
    ),
    "Coffee & cafes": ("cafe", "coffee_shop", "bakery", "bagel_shop", "juice_shop"),
    "Wine bars": ("bar", "pub", "irish_pub"),
    "Cocktail bars": ("bar", "pub", "irish_pub", "night_club"),
    "Live music": ("bar", "night_club", "event_venue", "pub"),
    "Rooftop / scenic": ("bar", "restaurant", "night_club", "american_restaurant"),
    "Outdoor dining": (
        "restaurant",
        "cafe",
        "american_restaurant",
        "mexican_restaurant",
        "brunch_restaurant",
        "seafood_restaurant",
    ),
    "Casual bites": (
        "fast_food_restaurant",
        "sandwich_shop",
        "pizza_restaurant",
        "bagel_shop",
        "bakery",
        "cafe",
        "diner",
        "mexican_restaurant",
    ),
    "Fine dining": (
        "steak_house",
        "french_restaurant",
        "seafood_restaurant",
        "sushi_restaurant",
        "japanese_restaurant",
        "restaurant",
    ),
    "Nightlife / dancing": ("night_club", "bar", "event_venue"),
    "Culture / galleries": ("cafe", "event_venue", "restaurant"),
    "Wellness": ("juice_shop", "cafe", "coffee_shop"),
    "Sports / active": ("sports_bar", "bar", "pub", "american_restaurant"),
    "Experiences / tasting menus": (
        "restaurant",
        "steak_house",
        "sushi_restaurant",
        "french_restaurant",
        "japanese_restaurant",
        "bar",
    ),
}


def neighbourhoods_for_city(city: str) -> list[str]:
    """Return forced neighbourhood options for a city (empty if unsupported)."""
    return list(NEIGHBOURHOODS_BY_CITY.get((city or "").strip(), []))


def preferred_types_from_activities(activities: list[str] | None) -> list[str]:
    """Flatten activity prefs into primary_type values for soft Discover ranking."""
    preferred: set[str] = set()
    for activity in activities or []:
        preferred.update(ACTIVITY_TO_PRIMARY_TYPES.get(str(activity).strip(), ()))
    return sorted(preferred)
