-- Fix: VENUE_SWIPER_APP cannot read STAGING_MARTS.DIM_PLACES
-- Run entire script in Snowsight as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;

-- 1) Confirm where dim_places lives (note TABLE_SCHEMA)
SHOW SCHEMAS LIKE '%MART%' IN DATABASE VENUE_HYPE;

SELECT table_schema, table_name, row_count
FROM VENUE_HYPE.INFORMATION_SCHEMA.TABLES
WHERE table_name = 'DIM_PLACES';

-- 2) Grants (schema USAGE is required before table SELECT)
GRANT USAGE ON WAREHOUSE VENUE_HYPE_WH TO ROLE VENUE_SWIPER_APP;
GRANT USAGE ON DATABASE VENUE_HYPE TO ROLE VENUE_SWIPER_APP;
GRANT USAGE ON SCHEMA VENUE_HYPE.STAGING_MARTS TO ROLE VENUE_SWIPER_APP;
GRANT SELECT ON TABLE VENUE_HYPE.STAGING_MARTS.DIM_PLACES TO ROLE VENUE_SWIPER_APP;
GRANT USAGE ON SCHEMA VENUE_HYPE.APP TO ROLE VENUE_SWIPER_APP;
GRANT SELECT, INSERT, UPDATE ON TABLE VENUE_HYPE.APP.VENUE_RATINGS TO ROLE VENUE_SWIPER_APP;

-- 3) Confirm grants (look for STAGING_MARTS and DIM_PLACES rows)
SHOW GRANTS TO ROLE VENUE_SWIPER_APP;

-- 4) Smoke test AS the service role (must return a number, not an error)
USE ROLE VENUE_SWIPER_APP;
USE WAREHOUSE VENUE_HYPE_WH;
USE DATABASE VENUE_HYPE;

SELECT CURRENT_USER(), CURRENT_ROLE();

SELECT COUNT(*) AS manhattan_beach_venues
FROM VENUE_HYPE.STAGING_MARTS.DIM_PLACES
WHERE borough = 'Manhattan Beach';
