-- Service account for Streamlit Community Cloud (Option B sharing)
-- Run as ACCOUNTADMIN in a Snowsight worksheet.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS VENUE_SWIPER_APP;

CREATE USER IF NOT EXISTS VENUE_SWIPER_SVC
    PASSWORD = 'CHANGE_ME_STRONG_PASSWORD'
    LOGIN_NAME = 'VENUE_SWIPER_SVC'
    DISPLAY_NAME = 'Venue Swiper Streamlit Cloud'
    DEFAULT_ROLE = VENUE_SWIPER_APP
    DEFAULT_WAREHOUSE = VENUE_HYPE_WH
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Backend user for external Streamlit app (Community Cloud)';

GRANT ROLE VENUE_SWIPER_APP TO USER VENUE_SWIPER_SVC;

GRANT USAGE ON WAREHOUSE VENUE_HYPE_WH TO ROLE VENUE_SWIPER_APP;
GRANT USAGE ON DATABASE VENUE_HYPE TO ROLE VENUE_SWIPER_APP;
GRANT USAGE ON SCHEMA VENUE_HYPE.APP TO ROLE VENUE_SWIPER_APP;

GRANT SELECT ON TABLE VENUE_HYPE.STAGING_MARTS.DIM_PLACES TO ROLE VENUE_SWIPER_APP;
GRANT SELECT, INSERT, UPDATE ON TABLE VENUE_HYPE.APP.VENUE_RATINGS TO ROLE VENUE_SWIPER_APP;

SELECT 'VENUE_SWIPER_SVC ready for Streamlit Cloud' AS STATUS;
